name: Main Pipeline

on:
  push:
    branches: [main]

jobs:

  heroku_deploy:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Deploy to heroku
      if: ${{ github.event_name == 'push' }}
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: "darkem"
        heroku_email: ${{ secrets.HEROKU_EMAIL }}
        appdir: "api"
      env:
        HD_EMAIL: ${{ secrets.EMAIL }}
        HD_PASSWORD: ${{ secrets.PASSWORD }}

  gh_deploy:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - run: |
        cd frontend
        npm ci
        npm run build
        cd ..
    - run: |
        mv frontend/src/public .
    - name: Deploy to GH Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: public
